# Stage 1: Build React app
FROM node:20-alpine AS build

WORKDIR /app

# Accept build-time environment variables from docker-compose
ARG BACKEND_URL
ENV VITE_API_URL=$BACKEND_URL

COPY package*.json tsconfig*.json tsconfig.node.json vite.config.ts index.html  public ./
RUN npm ci
COPY public ./public
COPY src ./src
COPY .env.*  .
RUN npm run build


# Stage 2: Serve with Nginx
FROM nginx:alpine

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

#  Copy React build
COPY --from=build /app/dist /usr/share/nginx/html


# Optional: custom error page
COPY nginx/404.html /usr/share/nginx/html

# Copy custom nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# COPY public/runtime-config.js /usr/share/nginx/html/runtime-config.js

# --- Runtime config injection ---
# Add entrypoint script
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Expose port
EXPOSE 80

# Start Nginx
ENTRYPOINT ["/docker-entrypoint.sh"]
